### ISSUE TITLE
Fixing readme errors

### ISSUE THREAD

**Issue by Anirudhdh** [koshev-msk/luci-app-smstools3#6]
There are some minor bugs to fix:

~~```cd feeds/luci/application/```~~
```cd feeds/luci/applications/```
~~```./scripts feeds update -a; ./scripts/feeds install -a```~~
```./scripts/feeds update -a; ./scripts/feeds install -a```

**Comment by koshev-msk** [comment]
fixed in https://github.com/koshev-msk/luci-app-smstools3/commit/6f53445494bab137edc2f0f7918bb4e95ad8c7ec
